# Generated by Django 4.1.3 on 2022-12-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prezents', '0003_alter_post_file_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
